In [1]:
import pandas as pd
import torch as t
import numpy as np
import matplotlib.pyplot as plt
import random

In [2]:
data=pd.read_csv(r"C:\Users\hrish\Projects\Deep_learning_projects\Trigram\NationalNames.csv")

In [3]:
names=data['Name'].unique()

In [4]:
random.seed(42)
names=list(names)
random.shuffle(names)

In [5]:
names=[n.lower() for n in names]

In [6]:
alpha=list(set(''.join(names)))
alpha.sort()

In [7]:
con={a:i+1 for i,a in enumerate(alpha)}
con['.']=0

In [8]:
X=[]
y=[]
for nm in names:
    ct=[0,0,0]
    nm=nm+'.'
    for c in nm:
        X.append(ct)
        y.append(con[c])
        ct=ct[1:]+[con[c]]

In [38]:
g = t.Generator().manual_seed(2147483647)
C = t.randn((27, 10), generator=g)
W1 = t.randn((30, 500), generator=g)*0
b1 = t.randn(500, generator=g)*0
W2= t.randn((500, 500), generator=g)*0
b2= t.randn(500, generator=g)*0
W3 = t.randn((500, 27), generator=g)*0
b3 = t.randn(27, generator=g)*0
parameters = [C, W1, b1, W2, b2, W3, b3]

In [39]:
for p in parameters:
    p.requires_grad=True

In [40]:
Xtr=t.tensor(X[:500001])
ytr=t.tensor(y[:500001])
Xts=t.tensor(X[500001:])
yts=t.tensor(y[500001:])

In [41]:
C[Xtr[:5]].view(-1,30)

tensor([[ 1.5674, -0.2373, -0.0274, -1.1008,  0.2859, -0.0296, -1.5471,  0.6049,
          0.0791,  0.9046,  1.5674, -0.2373, -0.0274, -1.1008,  0.2859, -0.0296,
         -1.5471,  0.6049,  0.0791,  0.9046,  1.5674, -0.2373, -0.0274, -1.1008,
          0.2859, -0.0296, -1.5471,  0.6049,  0.0791,  0.9046],
        [ 1.5674, -0.2373, -0.0274, -1.1008,  0.2859, -0.0296, -1.5471,  0.6049,
          0.0791,  0.9046,  1.5674, -0.2373, -0.0274, -1.1008,  0.2859, -0.0296,
         -1.5471,  0.6049,  0.0791,  0.9046,  1.3283, -1.0921, -0.8395,  0.1910,
         -0.7175, -0.3867, -1.2542,  1.2068, -1.7102, -0.4770],
        [ 1.5674, -0.2373, -0.0274, -1.1008,  0.2859, -0.0296, -1.5471,  0.6049,
          0.0791,  0.9046,  1.3283, -1.0921, -0.8395,  0.1910, -0.7175, -0.3867,
         -1.2542,  1.2068, -1.7102, -0.4770,  0.5557,  0.4746, -1.3867,  1.6229,
          0.1720,  0.9885,  0.5066,  1.0198, -1.9062, -0.4275],
        [ 1.3283, -1.0921, -0.8395,  0.1910, -0.7175, -0.3867, -1.2542,  1.2068

In [42]:
lr=1

In [43]:
lossi=[]
for i in range(40000):
    ix=t.randint(0,Xtr.shape[0],(1000,),generator=g)
    h1=C[Xtr[ix]].view(-1,30)@W1+b1
    h1=t.tanh(h1)
    h2=h1@W2+b2
    h2=t.tanh(h2)
    logits=h2@W3+b3
    loss=loss=t.nn.functional.cross_entropy(logits,ytr[ix])
    for p in parameters:
        p.grad=None
    loss.backward()
    if(i>20000):
        lr=0.1
    for p in parameters:
        p.data-=lr*p.grad
    lossi.append(loss)

In [44]:
lossi

[tensor(3.2958, grad_fn=<NllLossBackward0>),
 tensor(3.2598, grad_fn=<NllLossBackward0>),
 tensor(3.2233, grad_fn=<NllLossBackward0>),
 tensor(3.1917, grad_fn=<NllLossBackward0>),
 tensor(3.1559, grad_fn=<NllLossBackward0>),
 tensor(3.1268, grad_fn=<NllLossBackward0>),
 tensor(3.1156, grad_fn=<NllLossBackward0>),
 tensor(3.0651, grad_fn=<NllLossBackward0>),
 tensor(3.0559, grad_fn=<NllLossBackward0>),
 tensor(3.0497, grad_fn=<NllLossBackward0>),
 tensor(3.0317, grad_fn=<NllLossBackward0>),
 tensor(3.0215, grad_fn=<NllLossBackward0>),
 tensor(2.9935, grad_fn=<NllLossBackward0>),
 tensor(2.9783, grad_fn=<NllLossBackward0>),
 tensor(2.9854, grad_fn=<NllLossBackward0>),
 tensor(2.9694, grad_fn=<NllLossBackward0>),
 tensor(2.9608, grad_fn=<NllLossBackward0>),
 tensor(2.9442, grad_fn=<NllLossBackward0>),
 tensor(2.9580, grad_fn=<NllLossBackward0>),
 tensor(2.9204, grad_fn=<NllLossBackward0>),
 tensor(2.9578, grad_fn=<NllLossBackward0>),
 tensor(2.9147, grad_fn=<NllLossBackward0>),
 tensor(2.

In [45]:
b3

tensor([ 1.8567,  1.9762, -0.6721, -0.1012,  0.2752,  1.5501, -1.6314, -0.9671,
         0.5810,  1.2824, -0.3806, -0.0470,  1.0223,  0.2560,  1.3310,  0.5027,
        -1.5271, -1.9792,  1.0150,  0.6542,  0.4743, -0.2138, -0.7303, -1.5338,
        -2.5387,  0.5213, -0.9759], requires_grad=True)

In [47]:
W3

tensor([[-0., 0., 0.,  ..., -0., 0., 0.],
        [-0., -0., 0.,  ..., -0., 0., 0.],
        [0., -0., -0.,  ..., -0., -0., 0.],
        ...,
        [0., -0., -0.,  ..., -0., -0., 0.],
        [-0., -0., 0.,  ..., -0., 0., -0.],
        [0., 0., 0.,  ..., 0., -0., -0.]], requires_grad=True)

In [53]:
layers=[t.nn.Linear(30,500),t.nn.BatchNorm1d(500),t.nn.Tanh(),t.nn.Linear(500, 500),t.nn.BatchNorm1d(500),t.nn.Tanh(),t.nn.Linear(500, 27)]
parameters = [C] + [p for layer in layers for p in layer.parameters()]
for p in parameters:
  p.requires_grad = True

In [ ]:
lossi=[]
for i in range(40000):
    ix=t.randint(0,Xtr.shape[0],(1000,),generator=g)
    emb=C[Xtr[ix]].view(-1,30)
    res=emb
    for l in layers:
        res=l(res)
    loss=t.nn.functional.cross_entropy(res,ytr[ix])
    for p in parameters:
        p.grad=None
    loss.backward()
    if(i>20000):
        lr=0.1
    for p in parameters:
        p.data-=lr*p.grad
    lossi.append(loss)

In [ ]:
emb=C[Xtr]
res=emb
for l in layers:
    res=l(res)
loss=t.nn.functional.cross_entropy(res,ytr[ix])

In [ ]:
with torch.no_grad():
    k=layers[1].weight/((layers[1].running_var+layers[1].eps)**0.5)
    layers[0].weight=layers[0].weight*k.view(-1,1)
    layers[0].bias=k*(layers[0].bias-layers[1].running_mean)+layers[1].bias

In [54]:
with torch.no_grad():
    k=layers[4].weight/((layers[4].running_var+layers[4].eps)**0.5)
    layers[3].weight=layers[3].weight*k.view(-1,1)
    layers[3].bias=k*(layers[3].bias-layers[4].running_mean)+layers[4].bias

_IncompleteInputError: incomplete input (2096347946.py, line 1)

In [ ]:
new_layers=[layers[0]+layers[2]+layers[3]+layers[5]+layers[-1]]

In [ ]:
emb=C[Xtr]
res=emb
for l in new_layers:
    res=l(res)
loss=t.nn.functional.cross_entropy(res,ytr[ix])